"""empty message

Revision ID: c236fae9225a
Revises: 56665d35daf7
Create Date: 2020-04-22 09:25:12.224000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c236fae9225a'
down_revision = '56665d35daf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orders', 'orderss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('orderss', 'orders')
    # ### end Alembic commands ###
