"""empty message

Revision ID: a006b8836bcd
Revises: fb689aa72fce
Create Date: 2020-04-22 09:47:03.940513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a006b8836bcd'
down_revision = 'fb689aa72fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('member', 'location')
    with op.batch_alter_table('member') as batch_op:
        batch_op.drop_column('location')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('location', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
